/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { LikeWhereUniqueInput } from "../../like/base/LikeWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class User2UpdateInput {
  @ApiProperty({
    required: false,
    type: () => LikeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LikeWhereUniqueInput)
  @IsOptional()
  @Field(() => LikeWhereUniqueInput, {
    nullable: true,
  })
  updatedAt?: LikeWhereUniqueInput;
}

export { User2UpdateInput as User2UpdateInput };
