/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  User2 as PrismaUser2,
  Like as PrismaLike,
} from "@prisma/client";

export class User2ServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.User2CountArgs, "select">): Promise<number> {
    return this.prisma.user2.count(args);
  }

  async user2s(args: Prisma.User2FindManyArgs): Promise<PrismaUser2[]> {
    return this.prisma.user2.findMany(args);
  }
  async user2(args: Prisma.User2FindUniqueArgs): Promise<PrismaUser2 | null> {
    return this.prisma.user2.findUnique(args);
  }
  async createUser2(args: Prisma.User2CreateArgs): Promise<PrismaUser2> {
    return this.prisma.user2.create(args);
  }
  async updateUser2(args: Prisma.User2UpdateArgs): Promise<PrismaUser2> {
    return this.prisma.user2.update(args);
  }
  async deleteUser2(args: Prisma.User2DeleteArgs): Promise<PrismaUser2> {
    return this.prisma.user2.delete(args);
  }

  async getUpdatedAt(parentId: string): Promise<PrismaLike | null> {
    return this.prisma.user2
      .findUnique({
        where: { id: parentId },
      })
      .updatedAt();
  }
}
