/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { User2Service } from "../user2.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { User2CreateInput } from "./User2CreateInput";
import { User2 } from "./User2";
import { User2FindManyArgs } from "./User2FindManyArgs";
import { User2WhereUniqueInput } from "./User2WhereUniqueInput";
import { User2UpdateInput } from "./User2UpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class User2ControllerBase {
  constructor(
    protected readonly service: User2Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User2 })
  @nestAccessControl.UseRoles({
    resource: "User2",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUser2(@common.Body() data: User2CreateInput): Promise<User2> {
    return await this.service.createUser2({
      data: {
        ...data,

        updatedAt: {
          connect: data.updatedAt,
        },
      },
      select: {
        createdAt: true,
        id: true,

        updatedAt: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [User2] })
  @ApiNestedQuery(User2FindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User2",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async user2s(@common.Req() request: Request): Promise<User2[]> {
    const args = plainToClass(User2FindManyArgs, request.query);
    return this.service.user2s({
      ...args,
      select: {
        createdAt: true,
        id: true,

        updatedAt: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User2 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User2",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async user2(
    @common.Param() params: User2WhereUniqueInput
  ): Promise<User2 | null> {
    const result = await this.service.user2({
      where: params,
      select: {
        createdAt: true,
        id: true,

        updatedAt: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User2 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User2",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUser2(
    @common.Param() params: User2WhereUniqueInput,
    @common.Body() data: User2UpdateInput
  ): Promise<User2 | null> {
    try {
      return await this.service.updateUser2({
        where: params,
        data: {
          ...data,

          updatedAt: {
            connect: data.updatedAt,
          },
        },
        select: {
          createdAt: true,
          id: true,

          updatedAt: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User2 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "User2",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUser2(
    @common.Param() params: User2WhereUniqueInput
  ): Promise<User2 | null> {
    try {
      return await this.service.deleteUser2({
        where: params,
        select: {
          createdAt: true,
          id: true,

          updatedAt: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
