/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Retweet } from "./Retweet";
import { RetweetCountArgs } from "./RetweetCountArgs";
import { RetweetFindManyArgs } from "./RetweetFindManyArgs";
import { RetweetFindUniqueArgs } from "./RetweetFindUniqueArgs";
import { DeleteRetweetArgs } from "./DeleteRetweetArgs";
import { RetweetService } from "../retweet.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Retweet)
export class RetweetResolverBase {
  constructor(
    protected readonly service: RetweetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Retweet",
    action: "read",
    possession: "any",
  })
  async _retweetsMeta(
    @graphql.Args() args: RetweetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Retweet])
  @nestAccessControl.UseRoles({
    resource: "Retweet",
    action: "read",
    possession: "any",
  })
  async retweets(
    @graphql.Args() args: RetweetFindManyArgs
  ): Promise<Retweet[]> {
    return this.service.retweets(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Retweet, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Retweet",
    action: "read",
    possession: "own",
  })
  async retweet(
    @graphql.Args() args: RetweetFindUniqueArgs
  ): Promise<Retweet | null> {
    const result = await this.service.retweet(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Retweet)
  @nestAccessControl.UseRoles({
    resource: "Retweet",
    action: "delete",
    possession: "any",
  })
  async deleteRetweet(
    @graphql.Args() args: DeleteRetweetArgs
  ): Promise<Retweet | null> {
    try {
      return await this.service.deleteRetweet(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
